# GitLab CI in conjunction with GitLab Runner can use Docker Engine to test and build any application.
# Docker, when used with GitLab CI, runs each job in a separate and isolated container using the predefined image that is set up in .gitlab-ci.yml.
# In this case we use the latest python docker image to build and test this project.
image: $SKA_K8S_TOOLS_BUILD_DEPLOY

# cache is used to specify a list of files and directories which should be cached between jobs. You can only use paths that are within the project workspace.
# If cache is defined outside the scope of jobs, it means it is set globally and all jobs will use that definition
# cache:
#   paths:

stages:
  # - lint
  - build
  - test
#  - pages
  - publish
#  - scan



# Standardised included jobs
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MINIKUBE: "false"
  CI_POETRY_VERSION: "2.0.1"
  USE_CONAN: "true"
  CONAN_USER_CHANNEL: "marvin/stable"

# Include CI templates
include:

# Python
  # - project: 'ska-telescope/templates-repository'
  #   file: 'gitlab-ci/includes/python-lint.gitlab-ci.yml'
  # - project: 'ska-telescope/templates-repository'
  #   file: 'gitlab-ci/includes/python-build.gitlab-ci.yml'
  # - project: 'ska-telescope/templates-repository'
  #   file: 'gitlab-ci/includes/python-test.gitlab-ci.yml'

# Docs
  # - project: 'ska-telescope/templates-repository'
  #   file: 'gitlab-ci/includes/docs.gitlab-ci.yml'

# Release
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/release.gitlab-ci.yml'

# .post step finalisers eg: badges
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

# python-lint:
#   before_script:
#     - poetry config virtualenvs.in-project true
#     - echo "python-build Setting.. poetry config virtualenvs.create $POETRY_CONFIG_VIRTUALENVS_CREATE"
#     - poetry config virtualenvs.create $POETRY_CONFIG_VIRTUALENVS_CREATE
#     - |
#       if [[ -n $CI_POETRY_VERSION ]] && [[ $(poetry --version) != *$CI_POETRY_VERSION* ]]; then
#         echo "python-lint: Updating poetry to $CI_POETRY_VERSION";
#         time pipx upgrade poetry;
#       fi;

#       echo "python-lint: Installing with poetry";
#       time poetry install --all-extras;

.poetry-conan:
  before_script:
    - |
      if [[ -n $USE_CONAN ]] && [[ $USE_CONAN = "true" ]]; then
        poetry config virtualenvs.in-project true;
        echo "python-build Setting.. poetry config virtualenvs.create $POETRY_CONFIG_VIRTUALENVS_CREATE";
        poetry config virtualenvs.create $POETRY_CONFIG_VIRTUALENVS_CREATE;
        if [[ -n $CI_POETRY_VERSION ]] && [[ $(poetry --version) != *$CI_POETRY_VERSION* ]]; then
          echo "Updating poetry to $CI_POETRY_VERSION";
          time pipx upgrade poetry;
        fi;
        echo "Installing with poetry";
        time poetry install --all-extras --no-root;
      fi;

cpp-build-for-test:
  extends: 
    - .poetry-conan
  stage: build
  script:
    - apt-get update && apt-get install -y libboost-all-dev
    - make cpp-build-for-test USE_CONAN=$USE_CONAN
  artifacts:
    name: "$CI_COMMIT_REF_NAME-build-for-test"
    paths:
      - build_for_test/*
    expire_in: 1 d

cpp-build-for-release:
  extends: 
    - .poetry-conan
  stage: build
  only:
    - main
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - apt-get update && apt-get install -y libboost-all-dev
    - make cpp-build-for-release USE_CONAN=$USE_CONAN
  artifacts:
    name: "$CI_COMMIT_REF_NAME-build-for-release"
    paths:
      - build_for_release/*
    expire_in: 1 d

cpp-test:
  stage: test
  script:
    - make cpp-test
  artifacts:
    paths:
      - build_for_test/
    reports:
      junit: build_for_test/src/reports/unit-tests.xml

# Using a custom conan job instead of SKA template, as we don't know if SKA will maintain conan support in the future,
# however we need conan in this repo at least for now to be able to support the Talon (AA0.5/1) RDT.
cpp-publish:
  extends: 
    - .poetry-conan
  stage: publish
  dependencies: 
    - cpp-build
    - cpp-test
  only:
    - main
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - |
      cd build_for_release;
      if [[ -n $(USE_CONAN) ]] && [[ $(USE_CONAN) = "true" ]]; then
        CONAN_INFO=($(conan info ../conanfile.py -n None));
        CONAN_PKG_NAME=$(echo ${CONAN_INFO[1]} | awk -F/ '{print $1}' | tr -d "(");
        CONAN_PKG_VERSION=$(echo ${CONAN_INFO[1]} | awk -F/ '{print $2}' | tr -d ")");
        poetry run conan remote add conan-internal https://artefact.skao.int/repository/conan-internal/ true;
        poetry run conan user $CAR_CONAN_USERNAME -p $CAR_CONAN_PASSWORD -r conan-internal
        poetry run conan export-pkg -f . $CONAN_PKG_NAME/$CONAN_PKG_VERSION@$CONAN_USER_CHANNEL;
        poetry run conan upload --all -r conan-internal $CONAN_PKG_NAME/$CONAN_PKG_VERSION@$CONAN_USER_CHANNEL;
      else
        echo "Publishing raw binaries currently unsupported. May be added later if desired.";
      fi;
