set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_CROSSCOMPILING true)

set(tools /usr)
if(NOT CROSS_TARGET_SYSROOT_LOCATION)
  message( STATUS "Detected unset CROSS_TARGET_SYSROOT_LOCATION... setting to ${CMAKE_INSTALL_PREFIX}")
  set(CROSS_TARGET_SYSROOT_LOCATION ${CMAKE_INSTALL_PREFIX})
endif()

set(CMAKE_C_COMPILER ${tools}/bin/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER ${tools}/bin/aarch64-linux-gnu-g++)
set(CMAKE_AR ${tools}/bin/aarch64-linux-gnu-ar CACHE INTERNAL "")
set(CMAKE_LINKER ${tools}/bin/aarch64-linux-gnu-ld CACHE INTERNAL "")

set(CMAKE_FIND_ROOT_PATH ${CROSS_TARGET_SYSROOT_LOCATION})

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_PREFIX_PATH ${CROSS_TARGET_SYSROOT_LOCATION})